#!/usr/xbin/bash
 a="\033[30;1m"
 m="\033[31;1m"
 h="\033[32;1m"
 k="\033[33;1m"
 b="\033[34;1m"
 c="\033[35;1m"
 pu="\033[36;1m"
 p="\033[37;1m"
 m1="\033[38;1m"
 p2="\033[39;1m"
 hi="\033[40;1m"
 clear
 s="\033[31;1m╔"
 t="\033[31;1m╗"
 u="\033[31;1m║"
 z="${m}═════════════════════════════════"
 q="${m}════"
 j="${m}══════════"
 o="${m}╚"
 n="${m}╝"
 
 ulang="sh spam-sms.sh"
clear
echo "    ${s}${z}${t}"
echo "\033[031m       \033[1;91m_____    ____      __  __   _____ "
echo "\033[031m     \033[1;91m / ____|  / __ \    |  \/  | |_   _|"
echo "\033[031m    \033[1;92m | (___   | |  | |   | \  / |   | |  "
echo "\033[031m    \033[1;92m  \___ \  | |  | |   | |\/| |   | |  "
echo "\033[031m    \033[1;95m  ____) | | |__| |   | |  | |  _| |_ "
echo "\033[031m    \033[1;95m |_____/   \____/    |_|  |_| |_____|"
echo "    ${o}${z}${n}"
echo
echo "\033[031m╔══╗═══\033[033m╔═══════════════════╗"
echo "\033[031m|\033[030mNO\033[031m|   \033[031m|\033[037mMENU TOOLS\033[031m         |"
echo "\033[032m╚══╝═══\033[036m╚═══════════════════╝"
echo "${k}<═════════════════════════════════════════════>"
echo " ${a}╔═══════════════╗"
echo "\033[1;90m |\033[1;97mWITHOUT LOGIN \033[1;90m |"
echo " ${a}╚═══════════════╝"
echo "${p}[${h}1${p}] ${h} INDIA &  PAK CLONING \n${p}[${h}2${p}] ${k} BANGLA  CLONING ${p}"
echo
echo "${p}[${h}3${p}] ${pu} ALL IN ONE \n${p} ${p}[${h}4${p}] ${b} MAIL CLONING ${p}"
echo
echo " ${a}╔═══════════════╗"
echo "\033[1;90m |\033[1;97mWITH LOGIN   \033[1;90m  |"
echo " ${a}╚═══════════════╝"
echo "${p}[${h}05${p}] ${c} LOGIN WITH FACEBOOK ${p}「NEW」"
echo "${p}[${h}06${p}] ${h} TARGET ACCOUNT HACK${p}「NEW」"
echo
echo " ${a}╔═══════════════╗"
echo "\033[1;90m |\033[1;97mOTHERS            \033[1;90m  |"
echo " ${a}╚═══════════════╝"
echo "${p}[${h}07${p}] ${c} WHATSAPP VIRUS${p}「NEW」"
echo "${p}[${h}08${p}] ${K} HACK FB GROUP HACK${p}「NEW」"
echo "${p}[${h}00${p}] ${p2}CLOSE YOUR PROGRAM"
echo "${k}<═════════════════════════════════════════════>"
echo
echo "${p}"
echo " ${a}╔══════╗"
read -p " |SELECT|" r
echo " ╚══════╝"
if [ $r = 01 ] || [ $r = 1 ];then
sleep 1
python2 plo
sleep 2
cd Dashing-boy
python2 Dashing-boy.py
sleep 1
clear

fi

if [ $r = 02 ] || [ $r = 2 ];then
sleep 2
python2 plo
sleep 2
cd  digit
sh digit.sh
sleep 1
clear

fi

if [ $r = 03 ] || [ $r = 3 ];then
sleep 1
python2 plo
sleep 2
cd WORLD
python2 WORLD.py
sleep 2
clear

fi

if [ $r = 0 4 ] || [ $r = 4 ];then
sleep 1
python2 plo
sleep 2
cd Allmail
python2 Allmail.py
sleep 2
clear

fi

if [ $r = 05 ] || [ $r = 5 ];then
sleep 1
python2 plo
sleep 2
cd Monster
python2 Moon.py
sleep 2
clear

fi

if [ $r = 06 ] || [ $r = 6  ];then
sleep 1
python2 plo
sleep 2
cd WORLD
python2 fbbrute.py
sleep 2
clear

fi

if [ $r = 07 ] || [ $r = 7 ];then
sleep 1
python2 plo
sleep 2
cd brand
sh brands.sh
sleep 2
clear

fi

if [ $r = 08 ] || [ $r = 8 ];then
sleep 1
python2 plo
sleep 2
cd group_hack
python2 group.py
sleep 2
clear

fi

if [ $r = 00 ] || [ $r = 0 ];then
sleep 1

exit

else
echo "BACK MENU !"
sleep 2
sh digit.sh
fi
