#!/usr/bin/python2
#coding=utf-8
import os,sys,time,datetime,random,hashlib,re,threading,json,urllib,cookielib,requests,mechanize
from multiprocessing.pool import ThreadPool
from requests.exceptions import ConnectionError
from mechanize import Browser
session = requests.session()
os.system('clear')
base_url = 'https://mbasic.facebook.com'


reload(sys)
sys.setdefaultencoding('utf8')
br = mechanize.Browser()
br.set_handle_robots(False)
br.set_handle_refresh(mechanize._http.HTTPRefreshProcessor(),max_time=1)
br.addheaders = [('User-Agent', 'Opera/12.0 (Android; Opera Mini/52.2.2254/85. U; id) Presto/2.12.423 Version/12.16')]

def exb():
    print '[!] Exit Successful'
    os.sys.exit()

def jalan(z):
	for e in z + '\n':
		sys.stdout.write(e)
		sys.stdout.flush()
		time.sleep(3.0 / 200)

##### LICENSE #####
#=================#
def lisensi():
    os.system('clear')
    login()
####login#########
def login():
    try:
        cookie = open('sess.log', 'r').read().strip()
        main.start()
    except IOError:
        cookie = str(raw_input('  \x1b[1;93m[*] Input cookies: ')).strip()
        headers = {'User-Agent': 'Mozilla/5.0 (Linux; Android 4.2.1; en-us; Nexus 5 Build/JOP40D) AppleWebKit/535.19 (KHTML, like Gecko; googleweblight) Chrome/38.0.1025.166 Mobile Safari/535.19', 
           'Cookie': cookie}
        cookies = {'Cookie': cookie}
        response = requests.get(base_url + '/profile.php', cookies=cookies, headers=headers).text.encode('utf-8')
        if 'mbasic_logout_button' in str(response):
            response = requests.get(base_url + '/language.php', headers=headers, cookies=cookies).text.encode('utf-8')
            bs = parser(response, 'html.parser')
            href = bs.find('a', string='Urdu Pakistan', href=True)
            try:
                requests.get(base_url + href['href'], headers=headers, cookies=cookies)
            except:
                pass

            open('sess.log', 'w').write(cookie.strip())
            main.start()
        else:
            exit('  \x1b[1;91m[!] Cookies are not valid.\x1b[0m')

def start(self):
        response = self.requestGet(self.base_url)
        if 'mbasic_logout_button' not in str(response):
            os.remove('sess.log')
            sys.exit('  \x1b[1;91m\n[WARNING] Cookies tidak valid silahkan login kembali\x1b[0m')
	
    os.system('clear')
    os.system('train -f big ✯S O M I✯ -F gay')
    print 
    print
    print "\033[031m╔══╗═══\033[033m╔═══════════════════╗"
    print "\033[031m|\033[030mNO\033[031m|   \033[031m|\033[037mMENU TOOLS\033[031m         |"
    print "\033[032m╚══╝═══\033[036m╚═══════════════════╝"
    print "\033[1;94m<═════════════════════════════════════════════>"
    print " \033[1;96m  ╔═══════════════╗"
    print "\033[1;96m   |\033[1;97mWITHOUT LOGIN \033[1;96m |"
    print " \033[1;96m. ╚═══════════════╝"
    print"\033[1;92m1.\033[1;97m├\033[1;93m PAKISTAN WITHOUT LOGIN"
    print"\033[1;95m2.\033[1;97m├\033[1;93m MAIL WITHOUT LOGIN"
    print"\033[1;94m3.\033[1;97m├\033[1;93m TARGET WITHOUT LOGIN"
    print"\033[1;94m4.\033[1;97m├\033[1;93m BANGLADESH DIGIT CRACKING"
    print" \033[1;96m  ╔═══════════════╗"
    print"\033[1;96m   |\033[1;97mWITH LOGIN   \033[1;96m  |"
    print" \033[1;96m  ╚═══════════════╝"
    print"\033[1;93m4.\033[1;97m├\033[1;92m CRACKING WITH LOGIN"
    print"\033[1;91m5.\033[1;97m├\033[1;92m YAHOO WITH LOGIN"
    
    pilih_Somi()
    
def pilih_Somi():    
    Somi = raw_input("\n\033[1;97m>\033[1;93m")
    if Somi =="":
        print "\x1b[1;97mWRONG "
        pilih_Somi()
    elif Somi =="y":
    	os.system("rm -rf $HOME/WORLD")
        os.system("cd $HOME && git clone https://github.com/Somi190/WORLD.git")     
        
        time.sleep(5)
        os.system("cd $HOME/WORLD && python2 WORLD.py")
 
    elif Somi =="n":
    	exb()
    raw_input("\n\033[1;92m[\033[1;92mBack\033[1;95m]")
    login() 
          
if __name__ == '__main__':
    login()

